name: Snake Game

on:
  schedule: # execute every 12 hours
    - cron: "* */6 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: eron-moraes

          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-dark&theme=dark
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
