# name: Generate Datas

# on:
#   schedule: # execute every 12 hours
#     - cron: "0 */12 * * *"
#   workflow_dispatch:

# jobs:
#   build:
#     name: Generate Snake Animation
#     runs-on: ubuntu-latest

#     steps:
#       - name: Generate Snake SVG
#         uses: Platane/snk@v3
#         with:
#           github_user_name: eron-moraes
#           outputs: dist/github-contribution-grid-snake.svg

#           palette: github-dark

#       - name: Push to GitHub Pages
#         uses: crazy-max/ghaction-github-pages@v3
#         with:
#           target_branch: output
#           build_dir: dist
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: eron-moraes

          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-dark&theme=dark
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
